### ISSUE TITLE
Get "TypeError: __init__() got an unexpected keyword argument 'groups'" during ResNet init

### ISSUE THREAD

**Issue by aurotripathy** [facebookresearch/WSL-Images#3]
I'm using the starter code.

```
import torch
model = torch.hub.load('facebookresearch/WSL-Images', 'resnext101_32x8d_wsl')
model.eval()
```
Error is

```
Using cache found in /root/.cache/torch/hub/facebookresearch_WSL-Images_master
Traceback (most recent call last):
  File "test.py", line 3, in <module>
    model = torch.hub.load('facebookresearch/WSL-Images', 'resnext101_32x8d_wsl')
  File "/root/.local/lib/python3.6/site-packages/torch/hub.py", line 363, in load
    model = entry(*args, **kwargs)
  File "/root/.cache/torch/hub/facebookresearch_WSL-Images_master/hubconf.py", line 39, in resnext101_32x8d_wsl
    return _resnext('resnext101_32x8d', Bottleneck, [3, 4, 23, 3], True, progress, **kwargs)
  File "/root/.cache/torch/hub/facebookresearch_WSL-Images_master/hubconf.py", line 23, in _resnext
    model = ResNet(block, layers, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'groups'
```

**Comment by aurotripathy** [comment]
Does need torchvision 0.3.0 and I'm at torchvision 0.2.2. 
Closing, thanks.

**Comment by aurotripathy** [comment]
Does need torchvision 0.3.0 and I'm at torchvision 0.2.2.
Closing, thanks.
